"use strict";
let placeToVisit = ["America", "new york", "London", "Paris", "korea"];
// console.log(placeToVisit);
// console.log(placeToVisit.sort());
// console.log(placeToVisit);
// console.log(placeToVisit.sort().reverse());
// console.log(placeToVisit);
// console.log(placeToVisit.reverse());
// console.log(placeToVisit.reverse());
let sortedArray = ["America", "new york", "London", "Paris", "korea"];
sortedArray.sort();
console.log(sortedArray);
sortedArray.reverse();
console.log(sortedArray);
